# Generated by Django 4.2.15 on 2024-08-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
    ]
